#!/usr/bin/python3
# Copyright 2013 Matt Smith <matt@forsetti.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sys
from qif import QIF, QIFReader
from ldgwriter import LedgerWriter

source_file = None
target_file = None

args = sys.argv[1:]
while(args):
    if(source_file):
        target_file = args[0]
    else:
        source_file = args[0]
    del args[0]

source = open(source_file, 'r') if source_file else sys.stdin
target = open(target_file, 'w') if target_file else sys.stdout

qr = QIFReader(source)
ldg = LedgerWriter(target)
for record in qr:
    ldg.write(record.date, record.memo, record.amount,
              record.account_name, record.category)
source.close()
target.close()
